
ifndef::srcdir[:srcdir: ../../]
:rootdir: ../../../
:listing-caption: Listing

Links:

* link:https://jmini.github.io/asciidoctorj-gh-edit/[Project home] (this page)
* link:https://github.com/jmini/asciidoctorj-gh-edit/[GitHub project]
* link:https://bintray.com/jmini/maven/asciidoctorj-gh-edit[Binaries on Bintray]
* link:https://github.com/jmini/asciidoctorj-gh-edit/issues[Issue tracker]

TIP: Do you want to improve this page? Please gh:edit[link-text="edit it on GitHub", repository="jmini/asciidoctorj-gh-edit"].

== Usage

If you want to use the extension in your code, just write `gh:<mode>[<arguments>]`.
<<lst-all>> provides a complete example, using `view` as `mode` and several arguments:

[[lst-all, Listing 1]]
.Example using all possible arguments
[source,asciidoc]
----
include::{srcdir}test/resources/test_with_all-2.adoc[]
----

.Output (example with all arguments)
====
include::{srcdir}test/resources/test_with_all-2.adoc[]
====

=== Mode

The mode can be:

* `edit` (default used when the mode is unexpected)
* `view`

=== Arguments

==== Repository

The `repository` agurment specifies the repository on GitHub (pattern: `<owner>/<repository-name>`).
Depending on the case `<owner>` might be a GitHub user name or a GitHub organization name.
For the repository of this project it would be `jmini/asciidoctorj-gh-edit`.

The value can be defined as an attribute in the document.

==== Branch

The `branch` argument corresponds to the git branch that should be used.
If nothing is specified the default value `master` will be used.

The value can be defined as an attribute in the document.

==== Path

The `path` argument specifies the path of the file inside the repository.

If omitted, the path will be computed using the file location of the document beeing processed (value taken from the asciidoctor `docfile` attribute).
In order for this to work, the file needs to be located in one folder having the defined `<repository-name>` value in its name.

For example, for a file in this repository, this would a valid path:

    C:\git\asciidoctorj-gh-edit\src\docs\asciidoc\index.adoc

An other possibility is:

    ~/git/asciidoctorj-gh-edit_repo/src/docs/asciidoc/index.adoc


TIP: This means that if you are using this pluing on a continous integration server like jenkins, you should have a workspace name (derived from the job name) matching the git repository name.

In order to be able to compute the link correclty during the maven release process, a path containing two folders `target/checkout` is also considered as the root of the repository.

A valid path is:

    ~/buildjob/target/checkout/src/docs/asciidoc/index.adoc

If multiple possible roots are detected, the latest win.
Example:

    C:\git\asciidoctorj-gh-edit\target\checkout\src\docs\asciidoc\index.adoc

In this case the computed path is `src\docs\asciidoc\index.adoc`.

==== Link text

The `link-text` argument defines the text of the link. Default value is:

* "edit on GitHub" in the `edit` mode
* "view on GitHub" in the `view` mode

==== Link window

The `link-window` argument defines where the the link will be openend.
This is similar to the `window` attribute of the `link` macro.

The default value is empty (not set).

==== Server

The `server` argument is useful if you use your own Git Repository manager (the URL syntax needs to be compatible with GitHub. This is the case with GitLab).
Possible values are:

* `http://git.company.com/`
* `https://my.company.com/git-manager/`
* `https://my.company.com/git-manager` 

The trailing slash is not mandatory.

The value can be defined as an attribute in the document.

If nothing is specified the default value `https://github.com/` is used.

=== Additional examples

<<lst-empty>> demonstrates how you can use the macro without any arguments.
Please notice that in this case `repository` (and optionally `branch`) should be defined at document level. 

[[lst-empty, Listing 2]]
.Simple usage (no arguments)
[source,asciidoc]
----
include::{srcdir}test/resources/test_empty.adoc[]
----

.Output (simple usage)
====
include::{srcdir}test/resources/test_empty.adoc[]
====

As with any Asciidoctor Macro you can used position attribute instead of named attribute.
<<lst-twoattr>> provides an example with two arguments.

[[lst-twoattr, Listing 3]]
.Example with repository and branch as arguments (position attribute)
[source,asciidoc]
----
include::{srcdir}test/resources/test_with_branch-1.adoc[]
----

.Output (example with repository and branch)
====
include::{srcdir}test/resources/test_with_branch-1.adoc[]
====

<<lst-linktxt>> provides an example where the repository and the link text are specified as named attribute
You can also change the link text:

[[lst-linktxt, Listing 4]]
.Example with repository and link text as arguments (named attribute)
[source,asciidoc]
----
include::{srcdir}test/resources/test_with_link_text.adoc[]
----

.Output (example with repository and link text)
====
include::{srcdir}test/resources/test_with_link_text.adoc[]
====


=== Add the extension to your pom.xml file

The extension is the published on maven central.
You need to add an additional repository to your pom:

[source,xml]
----
include::{rootdir}pom.xml[tags=mvn-repo]
----

Then you need to declare `com.bsiag.asciidoctorj:gh-edit` as a dependency for the `org.asciidoctor:asciidoctor-maven-plugin` plugin.
Your `<build>` section could looks like this:

[source,xml]
----
include::{rootdir}pom.xml[tags=mvn-plugin]
----

=== Asciidoctorj version

This extension is build and tested with this version of asciidoctorj:

----
include::{rootdir}pom.xml[tags=mvn-adocj]
----
