:rootdir: ../../..
:github-readme: {rootdir}/README.adoc
:srcdir: {rootdir}/src/
:listing-caption: Listing
:revdate: {project-builddate}
:revnumber: {project-version}

include::{github-readme}[tags=vardef]

:projectpage: https://github.com/{gh-repo-owner}/{gh-repo-name}

include::{github-readme}[tags=header]

== URLs

* link:{homepage}[Project home] (this page)
* link:{projectpage}[GitHub project]
* link:{issues}[Issue tracker]

TIP: Do you want to improve this page? Please git-link:self[edit it on GitHub, edit].

== Description

If you want to use the extension in your code, just write `git-link&#58;<target>&#91;<arguments>&#93;`.
<<lst-all>> provides a complete example, that creates a link to edit a file on a GitHub repo:

[[lst-all, Listing 1]]
.Example using all possible arguments
[source,asciidoc]
----
include::{srcdir}test/resources/test_with_all-2.adoc[]
----

.Output (example with all arguments)
====
include::{srcdir}test/resources/test_with_all-2.adoc[]
====

[[sec-target, target argument]]
=== Target argument

This mandatory parameter defines the path of the ressource (a file or a directory) inside the git repository.

One possible value is `self`.
In that case the path will be computed using the file location of the document beeing processed (value taken from the asciidoctor `docfile` attribute).
In order to work, the file needs to be on a specific location.

The first possibility is to have a document located in a folder containing the `<repository-name>` value in its name.
For example, for a file in this repository, this would a valid path:

    C:\git\asciidoctorj-git-link\src\docs\asciidoc\index.adoc

The derived path for the link would be

    src/docs/asciidoc/index.adoc

An other possibility is:

    ~/git/asciidoctorj-git-link_repository/src/docs/asciidoc/index.adoc

TIP: This means that if you are using this plugin on a continous integration server like jenkins, you should have a workspace name (derived from the job name) matching the git repository name.

A second possibility is to use a location on a path containing the two folders `target/checkout`.
In that case the `checkout` folder will be considered as the root of the repository.
This is usefull when this plugin is used during a maven release process.

Example:

    ~/buildjob/target/checkout/src/docs/asciidoc/index.adoc

If multiple possible roots are detected, the latest win.
Example:

    C:\git\asciidoctorj-git-link\target\checkout\src\docs\asciidoc\index.adoc

In this last case the computed path is still: 

    src/docs/asciidoc/index.adoc


=== Additional arguments

The additional arguments are optional.
You can use the named form (as in <<lst-all>>) or use them in the correct order.

==== Link text

The `link-text` argument defines the text of the link. Default value is:

* "edit on GitHub" in the `edit` mode
* "view on GitHub" in the `view` and `viewdir` mode

==== Mode

The mode can be:

* `view`: view a file (default used when the mode is undefined or unexpected).
* `viewdir`: view a directory.
* `edit`: edit a file.

Alternatively to `view` or `viewdir` the mode can be set to `browse` to be compatible with some git servers.

When the <<sec-target>> ends with a slash (`/`), the defined mode is ignored and `viewdir` is used.

The value can be defined as `git-link-mode` attribute in the document.

[[sec-branch]]
==== Branch

The `branch` argument corresponds to the git branch that should be used.
If nothing is specified the default value `master` will be used.

The value can be defined as `git-branch` attribute in the document.

[[sec-repository]]
==== Repository

The `repository` agurment specifies the repository on GitHub (pattern: `<owner>/<repository-name>`).
Depending on the case `<owner>` might be a GitHub user name or a GitHub organization name.
For the repository of this project it would be `jmini/asciidoctorj-git-link`.

The value can be defined as `git-repository` attribute in the document.

==== Link window

The `link-window` argument defines where the the link will be openend.
This is similar to the `window` attribute of the `link` macro.

The default value is empty (not set).

[[sec-server]]
==== Server

The `server` argument is useful if you use your own Git Repository manager (the URL syntax needs to be compatible with GitHub. This is the case with GitLab).
Possible values are:

* `http://git.company.com/`
* `https://my.company.com/git/`
* `https://my.company.com/git-server` 

The trailing slash is not mandatory.

The value can be defined as `git-server` attribute in the document.

If nothing is specified the default value `https://github.com/` is used.

=== Additional examples

<<lst-empty>> demonstrates how you can use the macro without any arguments.
Please notice that in this case the argument <<sec-repository, repository>> (and optionally <<sec-branch, branch>> and <<sec-server, server>>) should be defined at document level. 

[[lst-empty, Listing 2]]
.Simple usage (no arguments)
[source,asciidoc]
----
include::{srcdir}test/resources/test_empty.adoc[]
----

.Output (simple usage)
====
include::{srcdir}test/resources/test_empty.adoc[]
====

As with any Asciidoctor Macro you can used position attribute instead of named attribute.
<<lst-twoattr>> provides an example with two arguments.

[[lst-twoattr, Listing 3]]
.Example with repository and branch as arguments (position attribute)
[source,asciidoc]
----
include::{srcdir}test/resources/test_with_branch-1.adoc[]
----

.Output (example with repository and branch)
====
include::{srcdir}test/resources/test_with_branch-1.adoc[]
====

<<lst-linktxt>> provides an example where the repository and the link text are specified as named attribute
You can also change the link text:

[[lst-linktxt, Listing 4]]
.Example with repository and link text as arguments (named attribute)
[source,asciidoc]
----
include::{srcdir}test/resources/test_with_link_text.adoc[]
----

.Output (example with repository and link text)
====
include::{srcdir}test/resources/test_with_link_text.adoc[]
====

== Usage

The extension is published on maven central and can be directly consumed from maven or gradle.

include::{rootdir}/usage/maven-example/README.adoc[leveloffset=1, tags=maven-integration]

For a complete example, see: git-link:usage/maven-example/pom.xml[pom.xml, branch="master"]

include::{rootdir}/usage/gradle-example/README.adoc[leveloffset=1, tags=gradle-integration]

For a complete example, see: git-link:usage/gradle-example/build.gradle[build.gradle, branch="master"]

== AsciidoctorJ version

This extension is compatible with `org.asciidoctor:asciidoctorj` in range `{asciidoctorj-version}`.

The continuous integration server runs the test suite with different AsciidoctorJ versions within this range.

=== Which version should I use?

Older version of this extension are compatible with older version of Asciidoctorj:

[cols="2*^"]
|===
| Asciidoctorj version | git-link&#58;&#91;&#93; version
| `1.5.x` | `3.0.0`
| `1.6.x` | `3.1.0`
| `2.x.x` | `3.2.0`
|===

== Download

The library is hosted on maven central.

[source, xml, subs="verbatim,attributes"]
.Maven coordinates of the library
----
<dependency>
  <groupId>fr.jmini.asciidoctorj</groupId>
  <artifactId>git-link</artifactId>
  <version>{last-stable-version}</version>
</dependency>
----

== Source Code

As for any java project, the source code of the plugin is available in the git-link:src/[src/] folder.

If you are using the Eclipse Installer (Oomph) you can use the `{oomph-file}` File (link:{setup}[url]) to setup your IDE properly.

=== Build

This project is using gradle.

Command to build the sources locally:

----
./gradlew build
----

Command to deploy to your local maven repository:

----
./gradlew publishToMavenLocal
----

Command to build the documentation page:

----
./gradlew asciidoctor
----

The output of this command is an HTML page located at `<git repo root>/build/docs/html5/index.html`.

==== For project maintainers

`signing.gnupg.keyName` and `signing.gnupg.passphrase` are expected to be set in your local `gradle.properties` file to be able to sign.
`sonatypeUser` and `sonatypePassword` are expected to be set in order to be able to publish to a distant repository.

Command to build and publish the result to maven central:

----
./gradlew publishToSonatype
----

Command to upload the documentation page on GitHub pages:

----
./gradlew gitPublishPush
----

Command to perform a release:

----
./gradlew release -Prelease.useAutomaticVersion=true
----

==== Using ssh-agent

Some tasks requires to push into the distant git repository (release task or updating the `gh-pages` branch).
If they are failing with errors like this:
----
org.eclipse.jgit.api.errors.TransportException: ... Permission denied (publickey).
---- 

Then `ssh-agent` can be used.
----
eval `ssh-agent -s`
ssh-add ~/.ssh/id_rsa
----
(link:https://superuser.com/a/990447/[source] for this approach)


include::{github-readme}[tags=contact-section]

include::{github-readme}[tags=license-section]

